import Head from 'next/head';
import Navbar from '../components/Navbar';
import UsersList from '../components/UsersList';

export default function Home() {
	return (
		<>
			<Head>
				<title>Masai Elective</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
			<UsersList />
		</>
	);
}
